# Generated by Django 3.2 on 2021-04-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codifier', models.CharField(max_length=50, unique=True, verbose_name='Кодификатор')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='EducationDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_form', models.CharField(choices=[('full_time', 'Очная'), ('part_time', 'Очно-заочная'), ('distance', 'Заочная')], max_length=9, verbose_name='Форма обучения')),
                ('duration', models.PositiveSmallIntegerField(help_text='В месяцах', verbose_name='Продолжительность')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Направление обучения',
                'verbose_name_plural': 'Направления обучения',
                'unique_together': {('specialization', 'education_form')},
            },
        ),
    ]
