# Generated by Django 3.2 on 2021-04-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdirection',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='specs.specialization', verbose_name='Специальность'),
        ),
    ]
