# Generated by Django 3.2 on 2021-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.CharField(max_length=128, verbose_name='Ключ источника данных')),
                ('slit_name', models.CharField(max_length=128, verbose_name='Ключ среза')),
                ('filters_data', models.JSONField(verbose_name='Информация по фильтрам')),
                ('columns_data', models.JSONField(verbose_name='Информация по колонкам')),
            ],
            options={
                'verbose_name': 'Сохраненный отчет',
                'verbose_name_plural': 'Сохраненные отчеты',
            },
        ),
    ]
