# Generated by Django 3.2 on 2021-04-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specs', '0002_alter_educationdirection_specialization'),
        ('organizations', '0002_educationorg_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('admitted_at', models.DateTimeField(verbose_name='Дата поступления')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('excluded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата исключения')),
                ('in_residence', models.BooleanField(verbose_name='Проживают в общежитии')),
                ('is_orphan', models.BooleanField(verbose_name='Дети-сироты, дети, оставшиеся без попечения родителей, лица из их числа')),
                ('is_handicapped', models.BooleanField(verbose_name='Инвалиды')),
                ('is_ovz', models.BooleanField(verbose_name='Лица с ОВЗ (имеется ПМПК)')),
                ('education_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.educationorg', verbose_name='Образовательное учреждение')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.educationdirection', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
