# Generated by Django 3.2 on 2021-04-18 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], db_index=True, default=0, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
