# Generated by Django 3.2 on 2021-04-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210418_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted_at',
            field=models.DateField(verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='due_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='excluded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исключения'),
        ),
    ]
