# Generated by Django 3.2 on 2021-04-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WsrOlympiadsStatus',
            new_name='WsrOlympiadStatus',
        ),
    ]
