# Generated by Django 3.2 on 2021-04-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_alter_educationdirection_specialization'),
        ('enrollee', '0002_rename_wsrolympiadsstatus_wsrolympiadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleespecialization',
            name='enrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='enrollee.enrollee', verbose_name='Абитуриент'),
        ),
        migrations.AlterField(
            model_name='enrolleespecialization',
            name='priority',
            field=models.SmallIntegerField(verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='enrolleespecialization',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.educationdirection', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='sportachievement',
            name='enrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_achievements', to='enrollee.enrollee', verbose_name='Абитуриент'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolleespecialization',
            unique_together={('priority', 'enrollee')},
        ),
    ]
