# Generated by Django 3.2 on 2021-04-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0005_enrollee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='citizenship',
            field=models.CharField(max_length=128, verbose_name='Гражданство'),
        ),
    ]
