# Generated by Django 3.2 on 2021-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollee", "0006_alter_enrollee_citizenship"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollee",
            name="sex",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Мужской"), (1, "Женский")], default=0
            ),
            preserve_default=False,
        ),
    ]
