# Generated by Django 3.2 on 2021-04-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0008_rename_insitution_graduatedinstitution_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол'),
        ),
    ]
