# Generated by Django 3.2 on 2021-04-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollee', '0009_alter_enrollee_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdoc',
            name='grade',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='birth_date',
            field=models.DateField(db_index=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='english',
            field=models.BooleanField(db_index=True, verbose_name='Английский язык'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(0, '5 классов'), (1, '9 классов'), (2, '11 классов'), (3, 'Среднее специальное образование'), (4, 'Неоконченное высшее'), (5, 'Высшее')], db_index=True, verbose_name='Уровень образование'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='has_goal_contract',
            field=models.BooleanField(db_index=True, verbose_name='Наличие договора о целевом обучении'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='is_handicapped',
            field=models.BooleanField(db_index=True, verbose_name='Инвалиды'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='is_orphan',
            field=models.BooleanField(db_index=True, verbose_name='Дети-сироты, дети, оставшиеся без попечения родителей, лица из их числа'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='is_ovz',
            field=models.BooleanField(db_index=True, verbose_name='Лица с ОВЗ (имеется ПМПК)'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='need_residence',
            field=models.BooleanField(db_index=True, verbose_name='Общежитие'),
        ),
        migrations.AlterField(
            model_name='enrollee',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], db_index=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='enrolleespecialization',
            name='priority',
            field=models.SmallIntegerField(db_index=True, verbose_name='Приоритет'),
        ),
    ]
