# Generated by Django 3.2 on 2021-04-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specs', '0003_alter_educationdirection_education_form'),
        ('organizations', '0002_educationorg_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('education_form', models.CharField(choices=[('budget', 'Бюджетная'), ('contract', 'Платная основа')], max_length=8, verbose_name='Форма обучения')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], db_index=True, verbose_name='Пол')),
                ('status', models.CharField(choices=[('employed', 'Трудоустроены'), ('employed_by_contract', 'Трудустроены согласно целевым договорам'), ('continue_education', 'Продолжили обучение'), ('not_employed', 'Не трудоустроены')], max_length=20, verbose_name='Статус')),
                ('education_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.educationorg', verbose_name='Образовательное учреждение')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.educationdirection', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
            },
        ),
    ]
